name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9.21"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover -s tests -p 'test*.py'

    - name: Check test coverage
      run: |
        coverage report --fail-under=80

    - name: Check documentation coverage
      run: |
        # -I ignores __init__.py files
        interrogate --fail-under=80 -vv ORM/ -I